import Head from "next/head";

const ProfileView = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-2 flex h-screen justify-center ">Profile view</main>
    </>
  );
};

export default ProfileView;
