import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, useUser } from "@clerk/nextjs";
import { CreatePostWizard, CommonFeed } from "@/components";
import { Layout } from "@/components/layout";

const Home: NextPage = () => {
  const { isSignedIn, isLoaded: isUserLoaded } = useUser();

  if (!isUserLoaded) {
    return <div></div>;
  }

  return (
    <>
      <Head>
        <title>Chirp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="flex border-b border-slate-400 p-4">
          {!isSignedIn && <SignInButton />}
          {isSignedIn && <CreatePostWizard />}
        </div>
        <CommonFeed />
      </Layout>
    </>
  );
};

export default Home;
